### ISSUE TITLE
TypeError on big tif picture

### ISSUE THREAD

**Issue by greut** [inveniosoftware/flask-iiif#16]
PIL panics on a big tif picture (54MB)

```
Traceback (most recent call last):
  File "/code/invenio/invenio/ext/legacy/__init__.py", line 124, in __call__
    response = self.app.full_dispatch_request()
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 270, in error_router
    return original_handler(e)
  File "/code/invenio/invenio/base/wrappers.py", line 125, in handle_user_exception
    return super(Flask, self).handle_user_exception(e)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 267, in error_router
    return self.handle_error(e)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 471, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask_restful/__init__.py", line 581, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask_iiif/decorators.py", line 56, in inner
    return f(*args, **kwargs)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask_iiif/decorators.py", line 38, in inner
    return f(*args, **kwargs)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask_iiif/restful.py", line 172, in get
    to_serve = image.serve(image_format=image_format)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/flask_iiif/api.py", line 379, in serve
    self.image.save(image_buffer, cleaned_image_format, quality=quality)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/PIL/Image.py", line 1665, in save
    save_handler(self, fp, filename)
  File "/home/invenio/.virtualenvs/maint-2.0/local/lib/python2.7/site-packages/PIL/PngImagePlugin.py", line 757, in _save
    data = name + b"\0\0" + zlib.compress(im.info["icc_profile"])
TypeError: must be string or read-only buffer, not tuple
```

* Flask-IIIF 0.2.0
* Pillow 3.0.0

**Comment by greut** [comment]
Nothing to do with Flask-IIIF: python-pillow/Pillow#1509
